name: Cria Pull Request com promessa cumprida

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BRANCH_NAME: cumprida-${{ github.run_id }}

on:
  workflow_dispatch:
    inputs:
      doc_path:
        type: string
        required: true
      fulfilled_date:
        type: string
        required: true
      links:
        type: string
        required: true
      comment:
        type: string
        default: "sem comentario"

jobs:
  promessa-cumprida:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - uses: actions/setup-node@v4
      - name: Node Install
        run: npm i
      - name: brach and update document
        run: |
          git checkout -b $BRANCH_NAME
          node scripts/update_doc.js ${{ inputs.doc_path }} ${{ inputs.fulfilled_date }} "${{ inputs.links }}"
          git add -A && git commit -m "Promessa ${{ inputs.doc_path }} cumprida!"
          git push --set-upstream origin $BRANCH_NAME
      - name: Create PR
        run: |
          echo -e "${{ inputs.comment }}\n\n---\n**DO NOT EDIT**\n\n\`docPath=${{ inputs.doc_path }}\`" > body.md
          gh pr create -B main --label "MARCAR-CUMPRIDA" --title "Promessa ${{ inputs.doc_path }} cumprida!" --body-file body.md
      - name: Redeploy website
        run: curl -X POST "${{ secrets.CLOUDFLARE_DEPLOY_HOOK_URL }}"
